# Generated by Django 5.2.6 on 2025-09-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_refreshtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RefreshToken",
        ),
    ]
