# Generated by Django 5.2.6 on 2025-09-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usertoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertoken",
            name="token",
            field=models.TextField(unique=True),
        ),
    ]
